services:
  producer-one:
    build:
      context: ./log-producer-one
      dockerfile: Dockerfile
    ports:
      - "3001:3001"

  producer-two:
    build:
      context: ./log-producer-two
      dockerfile: Dockerfile
    ports:
      - "3002:3002"