services:
  # ---------------------------------------------------------------------------
  # KAFKA MESSAGING LAYER (KRaft mode)
  # ---------------------------------------------------------------------------
  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    environment:
      #KRaft Engine Setup
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:29093'
      KAFKA_LISTENERS: 'PLAINTEXT://0.0.0.0:29092,CONTROLLER://0.0.0.0:29093,PLAINTEXT_HOST://0.0.0.0:9092'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      CLUSTER_ID: ${KAFKA_CLUSTER_ID}
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      #limit 1 GB
      KAFKA_LOG_RETENTION_BYTES: 1073741824
    ports:
      - "${PORT_KAFKA}:${PORT_KAFKA}"
    volumes:
      - ../kafka/data:/var/lib/kafka/data

  # kafka UI
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "${PORT_KAFKA_UI}:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092 # Use internal port
    depends_on:
      - kafka
    # ---------------------------------------------------------------------------
    # MONGO DATABASE LAYER (Headless & High-Throughput Optimized)
    # ---------------------------------------------------------------------------

  mongodb:
    image: mongo:8.0
    container_name: log_aggregator_db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    volumes:
        - mongo_data:/data/db
    # ---------------------------------------------------------------------------
    # Applications LAYER (2 Producers / 1 Consumer)
    # ---------------------------------------------------------------------------
  producer-one:
    build:
      context: ../log-producer-one
      dockerfile: Dockerfile
    container_name: producer-one
    ports:
      - "${PORT_PRODUCER_ONE}:3001"
    environment:
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:29092

  # =============================================
  # --- PRODUCER_2
  producer-two:
    build:
      context: ../log-producer-two
      dockerfile: Dockerfile
    container_name: producer-two
    ports:
      - "${PORT_PRODUCER_TWO}:3002"

    environment:
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:29092
  # =============================================
  # --- CONSUMER (Aggregator)
  aggregator:
    build:
      context: ../aggregator
      dockerfile: Dockerfile
    container_name: aggregator
    depends_on:
      - kafka
    environment:
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:29092
    ports:
      - "${PORT_AGGREGATOR}:3003"